#ifndef STRACE_H
# define STRACE_H

#include <stdio.h>      // printf and cie
#include <string.h>     // Basic C strings manipulation functions
#include <errno.h>      
#include <unistd.h>     // fork & cie
#include <inttypes.h>   // Using type denomination with number of bits. ex: int is uint32_t, addresse is uint64_t. Not for x86 so I should maybe use the char * word 
#include <sys/ptrace.h> // Lib for ptrace

#include "strace_errors.h"

# define SUCCESS  0
# define FAILURE  1

# define ARGC_MIN 2
# define INT "int"
# define MAX_N_ARGS  6   // Maximum number of arguments of a syscall

typedef struct  s_syscalls_l 
{
    int         n_args;                 /* Number of arguments of the syscall */
    char        *sys_name;              /* Name of the syscall */
    uint8_t     type_args[MAX_N_ARGS];  /* Array containing the type of each arguments of the syscall */
}               t_syscalls_l;


// [  0] =  3, "read", 		    },
// [  1] =  3, "write",		    },
// [  2] =  3, "open", 		    },
// [  3] =  1, "close"			    },
// [  4] =  2, "stat"			    },
// [  5] =  2, "fstat"			    },
// [  6] =  2, "lstat"			    },
// [  7] =  3, "poll"			    },
// [  8] =  3, "lseek"			    },
// [  9] =  6, "mmap"			    },
// [ 10] =  3, "mprotect"		    },
// [ 11] =  2, "munmap"		    },
// [ 12] =  1, "brk"			    },
// [ 13] =  4, "rt_sigaction"		},
// [ 14] =  4, "rt_sigprocmask"	},
// [ 15] =  0, "rt_sigreturn"		},
// [ 16] =  3, "ioctl"			    },
// [ 17] =  4, "pread64"		    },
// [ 18] =  4, "pwrite64"		    },
// [ 19] =  3, "readv"			    },
// [ 20] =  3, "writev"		    },
// [ 21] =  2, "access"		    },
// [ 22] =  1, "pipe"			    },
// [ 23] =  5, "select"		    },
// [ 24] =  0, "sched_yield"		},
// [ 25] =  5, "mremap"		    },
// [ 26] =  3, "msync"			    },
// [ 27] =  3, "mincore"		    },
// [ 28] =  3, "madvise"		    },
// [ 29] =  3, "shmget"		    },
// [ 30] =  3, "shmat"			},
// [ 31] =  3, "shmctl"		},
// [ 32] =  1, "dup"			},
// [ 33] =  2, "dup2"			},
// [ 34] =  0, "pause"			},
// [ 35] =  2, "nanosleep"		},
// [ 36] =  2, "getitimer"		},
// [ 37] =  1, "alarm"			},
// [ 38] =  3, "setitimer"		},
// [ 39] =  0, "getpid"		},
// [ 40] =  4, "sendfile"		},
// [ 41] =  3, "socket"		},
// [ 42] =  3, "connect"		},
// [ 43] =  3, "accept"		},
// [ 44] =  6, "sendto"		},
// [ 45] =  6, "recvfrom"		},
// [ 46] =  3, "sendmsg"		},
// [ 47] =  3, "recvmsg"		},
// [ 48] =  2, "shutdown"		},
// [ 49] =  3, "bind"			},
// [ 50] =  2, "listen"		},
// [ 51] =  3, "getsockname"		},
// [ 52] =  3, "getpeername"		},
// [ 53] =  4, "socketpair"		},
// [ 54] =  5, "setsockopt"		},
// [ 55] =  5, "getsockopt"		},
// [ 56] =  5, "clone"			},
// [ 57] =  0, "fork"			},
// [ 58] =  0, "vfork"			},
// [ 59] =  3, "execve"		},
// [ 60] =  1, "exit"			},
// [ 61] =  4, "wait4"			},
// [ 62] =  2, "kill"			},
// [ 63] =  1, "uname"			},
// [ 64] =  3, "semget"		},
// [ 65] =  3, "semop"			},
// [ 66] =  4, "semctl"		},
// [ 67] =  1, "shmdt"			},
// [ 68] =  2, "msgget"		},
// [ 69] =  4, "msgsnd"		},
// [ 70] =  5, "msgrcv"		},
// [ 71] =  3, "msgctl"		},
// [ 72] =  3, "fcntl"			},
// [ 73] =  2, "flock"			},
// [ 74] =  1, "fsync"			},
// [ 75] =  1, "fdatasync"		},
// [ 76] =  2, "truncate"		},
// [ 77] =  2, "ftruncate"		},
// [ 78] =  3, "getdents"		},
// [ 79] =  2, "getcwd"		},
// [ 80] =  1, "chdir"			},
// [ 81] =  1, "fchdir"		},
// [ 82] =  2, "rename"		},
// [ 83] =  2, "mkdir"			},
// [ 84] =  1, "rmdir"			},
// [ 85] =  2, "creat"			},
// [ 86] =  2, "link"			},
// [ 87] =  1, "unlink"		},
// [ 88] =  2, "symlink"		},
// [ 89] =  3, "readlink"		},
// [ 90] =  2, "chmod"			},
// [ 91] =  2, "fchmod"		},
// [ 92] =  3, "chown"			},
// [ 93] =  3, "fchown"		},
// [ 94] =  3, "lchown"		},
// [ 95] =  1, "umask"			},
// [ 96] =  2, "gettimeofday"		},
// [ 97] =  2, "getrlimit"		},
// [ 98] =  2, "getrusage"		},
// [ 99] =  1, "sysinfo"		},
// [100] =  1, "times"			},
// [101] =  4, "ptrace"		},
// [102] =  0, "getuid"		},
// [103] =  3, "syslog"		},
// [104] =  0, "getgid"		},
// [105] =  1, "setuid"		},
// [106] =  1, "setgid"		},
// [107] =  0, "geteuid"		},
// [108] =  0, "getegid"		},
// [109] =  2, "setpgid"		},
// [110] =  0, "getppid"		},
// [111] =  0, "getpgrp"		},
// [112] =  0, "setsid"		},
// [113] =  2, "setreuid"		},
// [114] =  2, "setregid"		},
// [115] =  2, "getgroups"		},
// [116] =  2, "setgroups"		},
// [117] =  3, "setresuid"		},
// [118] =  3, "getresuid"		},
// [119] =  3, "setresgid"		},
// [120] =  3, "getresgid"		},
// [121] =  1, "getpgid"		},
// [122] =  1, "setfsuid"		},
// [123] =  1, "setfsgid"		},
// [124] =  1, "getsid"		},
// [125] =  2, "capget"		},
// [126] =  2, "capset"		},
// [127] =  2, "rt_sigpending"		},
// [128] =  4, "rt_sigtimedwait"	},
// [129] =  3, "rt_sigqueueinfo"	},
// [130] =  2, "rt_sigsuspend"		},
// [131] =  2, "sigaltstack"		},
// [132] =  2, "utime"			},
// [133] =  3, "mknod"			},
// [134] =  1, "uselib"		},
// [135] =  1, "personality"		},
// [136] =  2, "ustat"			},
// [137] =  2, "statfs"		},
// [138] =  2, "fstatfs"		},
// [139] =  3, "sysfs"			},
// [140] =  2, "getpriority"		},
// [141] =  3, "setpriority"		},
// [142] =  2, "sched_setparam"	},
// [143] =  2, "sched_getparam"	},
// [144] =  3, "sched_setscheduler"	},
// [145] =  1, "sched_getscheduler"	},
// [146] =  1, "sched_get_priority_max"},
// [147] =  1, "sched_get_priority_min"},
// [148] =  2, "sched_rr_get_interval"},
// [149] =  2, "mlock"			},
// [150] =  2, "munlock"		},
// [151] =  1, "mlockall"		},
// [152] =  0, "munlockall"		},
// [153] =  0, "vhangup"		},
// [154] =  3, "modify_ldt"		},
// [155] =  2, "pivot_root"		},
// [156] =  1, "_sysctl"		},
// [157] =  5, "prctl"			},
// [158] =  2, "arch_prctl"		},
// [159] =  1, "adjtimex"		},
// [160] =  2, "setrlimit"		},
// [161] =  1, "chroot"		},
// [162] =  0, "sync"			},
// [163] =  1, "acct"			},
// [164] =  2, "settimeofday"		},
// [165] =  5, "mount"			},
// [166] =  2, "umount2"		},
// [167] =  2, "swapon"		},
// [168] =  1, "swapoff"		},
// [169] =  4, "reboot"		},
// [170] =  2, "sethostname"		},
// [171] =  2, "setdomainname"		},
// [172] =  1, "iopl"			},
// [173] =  3, "ioperm"		},
// [174] =  2, "create_module"		},
// [175] =  3, "init_module"		},
// [176] =  2, "delete_module"		},
// [177] =  1, "get_kernel_syms"	},
// [178] =  5, "query_module"		},
// [179] =  4, "quotactl"		},
// [180] =  3, "nfsservctl"		},
// [181] =  5, "getpmsg"		},
// [182] =  5, "putpmsg"		},
// [183] =  5, "afs_syscall"		},
// [184] =  3, "tuxcall"		},
// [185] =  3, "security"		},
// [186] =  0, "gettid"		},
// [187] =  3, "readahead"		},
// [188] =  5, "setxattr"		},
// [189] =  5, "lsetxattr"		},
// [190] =  5, "fsetxattr"		},
// [191] =  4, "getxattr"		},
// [192] =  4, "lgetxattr"		},
// [193] =  4, "fgetxattr"		},
// [194] =  3, "listxattr"		},
// [195] =  3, "llistxattr"		},
// [196] =  3, "flistxattr"		},
// [197] =  2, "removexattr"		},
// [198] =  2, "lremovexattr"		},
// [199] =  2, "fremovexattr"		},
// [200] =  2, "tkill"			},
// [201] =  1, "time"			},
// [202] =  6, "futex"			},
// [203] =  3, "sched_setaffinity"	},
// [204] =  3, "sched_getaffinity"	},
// [205] =  1, "set_thread_area"	},
// [206] =  2, "io_setup"		},
// [207] =  1, "io_destroy"		},
// [208] =  5, "io_getevents"		},
// [209] =  3, "io_submit"		},
// [210] =  3, "io_cancel"		},
// [211] =  1, "get_thread_area"	},
// [212] =  3, "lookup_dcookie"	},
// [213] =  1, "epoll_create"		},
// [214] =  4, "epoll_ctl_old"		},
// [215] =  4, "epoll_wait_old"	},
// [216] =  5, "remap_file_pages"	},
// [217] =  3, "getdents64"		},
// [218] =  1, "set_tid_address"	},
// [219] =  0, "restart_syscall"	},
// [220] =  4, "semtimedop"		},
// [221] =  4, "fadvise64"		},
// [222] =  3, "timer_create"		},
// [223] =  4, "timer_settime"		},
// [224] =  2, "timer_gettime"		},
// [225] =  1, "timer_getoverrun"	},
// [226] =  1, "timer_delete"		},
// [227] =  2, "clock_settime"		},
// [228] =  2, "clock_gettime"		},
// [229] =  2, "clock_getres"		},
// [230] =  4, "clock_nanosleep"	},
// [231] =  1, "exit_group"		},
// [232] =  4, "epoll_wait"		},
// [233] =  4, "epoll_ctl"		},
// [234] =  3, "tgkill"		},
// [235] =  2, "utimes"		},
// [236] =  5, "vserver"		},
// [237] =  6, "mbind"			},
// [238] =  3, "set_mempolicy"		},
// [239] =  5, "get_mempolicy"		},
// [240] =  4, "mq_open"		},
// [241] =  1, "mq_unlink"		},
// [242] =  5, "mq_timedsend"		},
// [243] =  5, "mq_timedreceive"	},
// [244] =  2, "mq_notify"		},
// [245] =  3, "mq_getsetattr"		},
// [246] =  4, "kexec_load"		},
// [247] =  5, "waitid"		},
// [248] =  5, "add_key"		},
// [249] =  4, "request_key"		},
// [250] =  5, "keyctl"		},
// [251] =  3, "ioprio_set"		},
// [252] =  2, "ioprio_get"		},
// [253] =  0, "inotify_init"		},
// [254] =  3, "inotify_add_watch"	},
// [255] =  2, "inotify_rm_watch"	},
// [256] =  4, "migrate_pages"		},
// [257] =  4, "openat"		},
// [258] =  3, "mkdirat"		},
// [259] =  4, "mknodat"		},
// [260] =  5, "fchownat"		},
// [261] =  3, "futimesat"		},
// [262] =  4, "newfstatat"		},
// [263] =  3, "unlinkat"		},
// [264] =  4, "renameat"		},
// [265] =  5, "linkat"		},
// [266] =  3, "symlinkat"		},
// [267] =  4, "readlinkat"		},
// [268] =  3, "fchmodat"		},
// [269] =  3, "faccessat"		},
// [270] =  6, "pselect6"		},
// [271] =  5, "ppoll"			},
// [272] =  1, "unshare"		},
// [273] =  2, "set_robust_list"	},
// [274] =  3, "get_robust_list"	},
// [275] =  6, "splice"		},
// [276] =  4, "tee"			},
// [277] =  4, "sync_file_range"	},
// [278] =  4, "vmsplice"		},
// [279] =  6, "move_pages"		},
// [280] =  4, "utimensat"		},
// [281] =  6, "epoll_pwait"		},
// [282] =  3, "signalfd"		},
// [283] =  2, "timerfd_create"	},
// [284] =  1, "eventfd"		},
// [285] =  4, "fallocate"		},
// [286] =  4, "timerfd_settime"	},
// [287] =  2, "timerfd_gettime"	},
// [288] =  4, "accept4"		},
// [289] =  4, "signalfd4"		},
// [290] =  2, "eventfd2"		},
// [291] =  1, "epoll_create1"		},
// [292] =  3, "dup3"			},
// [293] =  2, "pipe2"			},
// [294] =  1, "inotify_init1"		},
// [295] =  4, "preadv"		},
// [296] =  4, "pwritev"		},
// [297] =  4, "rt_tgsigqueueinfo"	},
// [298] =  5, "perf_event_open"	},
// [299] =  5, "recvmmsg"		},
// [300] =  2, "fanotify_init"		},
// [301] =  5, "fanotify_mark"		},
// [302] =  4, "prlimit64"		},
// [303] =  5, "name_to_handle_at"	},
// [304] =  3, "open_by_handle_at"	},
// [305] =  2, "clock_adjtime"		},
// [306] =  1, "syncfs"		},
// [307] =  4, "sendmmsg"		},
// [308] =  2, "setns"			},
// [309] =  3, "getcpu"		},
// [310] =  6, "process_vm_readv"	},
// [311] =  6, "process_vm_writev"	},
// [312] =  5, "kcmp"			},
// [313] =  3, "finit_module"		},
// [314] =  3, "sched_setattr"		},
// [315] =  4, "sched_getattr"		},
// [316] =  5, "renameat2"		},
// [317] =  3, "seccomp"		},
// [318] =  3, "getrandom"		},
// [319] =  2, "memfd_create"		},
// [320] =  5, "kexec_file_load"	},
// [321] =  3, "bpf"			},
// [322] =  5, "execveat"		},
// [323] =  1, "userfaultfd"		},
// [324] =  3, "membarrier"		},
// [325] =  3, "mlock2"		},
// [326] =  6, "copy_file_range"	},
// [327] =  6, "preadv2"		},
// [328] =  6, "pwritev2"		},
// [329] =  4, "pkey_mprotect"		},
// [330] =  2, "pkey_alloc"		},
// [331] =  1, "pkey_free"		},
// [332] =  5, "statx"			},
// [333] =  6, "io_pgetevents"		},
// [334] =  4, "rseq"			},
// [424] =  3, "pidfd_send_signal"}
// [425] =  2, "io_uring_setup"}
// [426] =  5, "io_uring_enter"}
// [427] =  4, "io_uring_register"}r
// [428] = "open_tree"}
// [429] = "move_mount"}
// [430] = "fsopen"}
// [431] = "fsconfig"}
// [432] = "fsmount"}
// [433] = "fspick"}
// [434] = "pidfd_open"}
// [435] = "clone3"}
// [436] = "close_range"}
// [437] = "openat2"}
// [438] = "pidfd_getfd"}
// [439] = "faccessat2"}
// [440] = "process_madvise"}
// [441] = "epoll_pwait2"}
// [442] = "mount_setattr"}
// [443] = "quotactl_fd"}
// [444] = "landlock_create_ruleset"}
// [445] = "landlock_add_rule"}
// [446] = "landlock_restrict_self"}
// [447] = "memfd_secret"}
// [448] = "process_mrelease"}
// [449] = "futex_waitv"}


// [0] = ["read", 3, unsigned int|char*|size_t]
// [1] = ["write", 3, unsigned int|const char*|size_t]
// [2] = ["open", 3, const char*|int|umode_t]
// [3] = ["close", 1, unsigned int]
// [4] = ["stat", 2, const char*|struct stat*]
// [5] = ["fstat", 2, unsigned int|struct stat*]
// [6] = ["lstat", 2, const char*|struct stat*]
// [7] = ["poll", 3, struct pollfd*|unsigned int|int]
// [8] = ["lseek", 3, unsigned int|off_t|unsigned int]
// [9] = ["mmap", 6, unsigned long|unsigned long|int|int|int|off_t]
// [10] = ["mprotect", 3, unsigned long|size_t|int]
// [11] = ["munmap", 2, unsigned long|size_t]
// [12] = ["brk", 1, unsigned long]
// [13] = ["rt_sigaction", 4, int|const struct sigaction*|struct sigaction*|size_t]
// [14] = ["rt_sigprocmask", 4, int|sigset_t*|sigset_t*|size_t]
// [15] = ["rt_sigreturn", 1, unsigned long]
// [16] = ["ioctl", 3, unsigned int|unsigned int|unsigned long]
// [17] = ["pread64", 4, unsigned int|char*|size_t|loff_t]
// [18] = ["pwrite64", 4, unsigned int|const char*|size_t|loff_t]
// [19] = ["readv", 3, unsigned long|const struct iovec*|unsigned long]
// [20] = ["writev", 3, unsigned long|const struct iovec*|unsigned long]
// [21] = ["access", 2, const char*|int]
// [22] = ["pipe", 1, int*]
// [23] = ["select", 5, int|fd_set*|fd_set*|fd_set*|struct timeval*]
// [24] = ["sched_yield", 0]
// [25] = ["mremap", 5, unsigned long|unsigned long|unsigned long|int|int|unsigned long]
// [26] = ["msync", 3, unsigned long|size_t|int]
// [27] = ["mincore", 3, unsigned long|size_t|unsigned char*]
// [28] = ["madvise", 3, unsigned long|size_t|int]
// [29] = ["shmget", 3, key_t|size_t|int]
// [30] = ["shmat", 3, int|char*|int]
// [31] = ["shmctl", 3, int|int|struct shmid_ds*]
// [32] = ["dup", 1, unsigned int]
// [33] = ["dup2", 2, unsigned int|unsigned int]
// [34] = ["pause", 0]
// [35] = ["nanosleep", 2, struct timespec*|struct timespec*]
// [36] = ["getitimer", 2, int|struct itimerval*]
// [37] = ["alarm", 1, unsigned int]
// [38] = ["setitimer", 3, int|struct itimerval*|struct itimerval*]
// [39] = ["getpid", 0]
// [40] = ["sendfile", 4, int|int|off_t*|size_t]
// [41] = ["socket", 3, int|int|int]
// [42] = ["connect", 3, int|struct sockaddr*|int]
// [43] = ["accept", 3, int|struct sockaddr*|int*]
// [44] = ["sendto", 6, int|void*|size_t|unsigned|struct sockaddr*|int]
// [45] = ["recvfrom", 6, int|void*|size_t|unsigned|struct sockaddr*|int*]
// [46] = ["sendmsg", 3, int|struct user_msghdr*|unsigned]
// [47] = ["recvmsg", 3, int|struct user_msghdr*|unsigned]
// [48] = ["shutdown", 2, int|int]
// [49] = ["bind", 3, int|struct sockaddr*|int]
// [50] = ["listen", 2, int|int]
// [51] = ["getsockname", 3, int|struct sockaddr*|int*]
// [52] = ["getpeername", 3, int|struct sockaddr*|int*]
// [53] = ["socketpair", 4, int|int|int|int*]
// [54] = ["setsockopt", 5, int|int|int|void*|int]
// [55] = ["getsockopt", 5, int|int|int|void*|int*]
// [56] = ["clone", 5, unsigned long|unsigned long|int*|void*|int*]
// [57] = ["fork", 0]
// [58] = ["vfork", 0]
// [59] = ["execve", 3, const char*|const char* const*|const char* const*]
// [60] = ["exit", 1, int]
// [61] = ["wait4", 4, pid_t|int*|int|int*]
// [62] = ["kill", 2, pid_t|int]
// [63] = ["uname", 1, struct old_utsname*]
// [64] = ["semget", 3, key_t|int|int]
// [65] = ["semop", 3, int|struct sembuf*|unsigned int]
// [66] = ["semctl", 4, int|int|int|union semun]
// [67] = ["shmdt", 1, char*]
// [68] = ["msgget", 2, key_t|int]
// [69] = ["msgsnd", 4, int|const void*|size_t|int]
// [70] = ["msgrcv", 5, int|void*|size_t|long|int]
// [71] = ["msgctl", 3, int|int|struct msqid_ds*]
// [72] = ["fcntl", 3, unsigned int|unsigned int|unsigned long]
// [73] = ["flock", 2, unsigned int|int]
// [74] = ["fsync", 1, unsigned int]
// [75] = ["fdatasync", 1, unsigned int]
// [76] = ["truncate", 2, const char*|long]
// [77] = ["ftruncate", 2, unsigned int|unsigned long]
// [78] = ["getdents", 3, unsigned int|struct linux_dirent*|unsigned int]
// [79] = ["getcwd", 2, char*|unsigned long]
// [80] = ["chdir", 1, const char*]
// [81] = ["fchdir", 1, unsigned int]
// [82] = ["rename", 2, const char*|const char*]
// [83] = ["mkdir", 2, const char*|umode_t]
// [84] = ["rmdir", 1, const char*]
// [85] = ["creat", 2, const char*|umode_t]
// [86] = ["link", 2, const char*|const char*]
// [87] = ["unlink", 1, const char*]
// [88] = ["symlink", 2, const char*|const char*]
// [89] = ["readlink", 3, const char*|char*|int]
// [90] = ["chmod", 2, const char*|umode_t]
// [91] = ["fchmod", 2, unsigned int|umode_t]
// [92] = ["chown", 3, const char*|uid_t|gid_t]
// [93] = ["fchown", 3, unsigned int|uid_t|gid_t]
// [94] = ["lchown", 3, const char*|uid_t|gid_t]
// [95] = ["umask", 1, int]
// [96] = ["gettimeofday", 2, struct timeval*|struct timezone*]
// [97] = ["getrlimit", 2, unsigned int|struct rlimit*]
// [98] = ["getrusage", 2, int|struct rusage*]
// [99] = ["sysinfo", 1, struct sysinfo*]
// [100] = ["times", 1, struct tms*]
// [101] = ["ptrace", 4, long|pid_t|void*|void*]
// [102] = ["getuid", 0]
// [103] = ["syslog", 3, int|char*|int]
// [104] = ["getgid", 0]
// [105] = ["setuid", 1, uid_t]
// [106] = ["setgid", 1, gid_t]
// [107] = ["geteuid", 0]
// [108] = ["getegid", 0]
// [109] = ["setpgid", 2, pid_t|pid_t]
// [110] = ["getppid", 0]
// [111] = ["getpgrp", 0]
// [112] = ["setsid", 0]
// [113] = ["setreuid", 2, uid_t|uid_t]
// [114] = ["setregid", 2, gid_t|gid_t]
// [115] = ["getgroups", 2, int|gid_t[]]
// [116] = ["setgroups", 2, size_t|gid_t[]]
// [117] = ["setresuid", 3, uid_t|uid_t|uid_t]
// [118] = ["getresuid", 3, uid_t*|uid_t*|uid_t*]
// [119] = ["setresgid", 3, gid_t|gid_t|gid_t]
// [120] = ["getresgid", 3, gid_t*|gid_t*|gid_t*]
// [121] = ["getpgid", 1, pid_t]
// [122] = ["setfsuid", 1, uid_t]
// [123] = ["setfsgid", 1, gid_t]
// [124] = ["getsid", 1, pid_t]
// [125] = ["capget", 2, cap_user_header_t|cap_user_data_t]
// [126] = ["capset", 2, cap_user_header_t|const cap_user_data_t]
// [127] = ["rt_sigpending", 2, sigset_t*|size_t]
// [128] = ["rt_sigtimedwait", 4, const sigset_t*|siginfo_t*|const struct timespec*|size_t]
// [129] = ["rt_sigqueueinfo", 3, pid_t|int|siginfo_t*]
// [130] = ["rt_sigsuspend", 2, sigset_t*|size_t]
// [131] = ["sigaltstack", 2, const stack_t*|stack_t*]
// [132] = ["utime", 2, char*|struct utimbuf*]
// [133] = ["mknod", 3, const char*|umode_t|dev_t]
// [134] = ["uselib", 1, const char*]
// [135] = ["personality", 1, unsigned long]
// [136] = ["ustat", 2, unsigned|struct ustat*]
// [137] = ["statfs", 2, const char*|struct statfs*]
// [138] = ["fstatfs", 2, unsigned int|struct statfs*]
// [139] = ["sysfs", 3, int|char*|void*]
// [140] = ["getpriority", 2, int|int|int]
// [141] = ["setpriority", 3, int|int|int]
// [142] = ["sched_setparam", 2, pid_t|struct sched_param*]
// [143] = ["sched_getparam", 2, pid_t|struct sched_param*]
// [144] = ["sched_setscheduler", 3, pid_t|int|struct sched_param*]
// [145] = ["sched_getscheduler", 1, pid_t]
// [146] = ["sched_get_priority_max", 1, int]
// [147] = ["sched_get_priority_min", 1, int]
// [148] = ["sched_rr_get_interval", 2, pid_t|struct timespec*]
// [149] = ["mlock", 2, unsigned long|size_t]
// [150] = ["munlock", 2, unsigned long|size_t]
// [151] = ["mlockall", 1, int]
// [152] = ["munlockall", 0]
// [153] = ["vhangup", 0]
// [154] = ["modify_ldt", 3, int|void*|unsigned long]
// [155] = ["pivot_root", 2, const char*|const char*]
// [156] = ["_sysctl", 1, struct __sysctl_args*]
// [157] = ["prctl", 5, int|unsigned long|unsigned long|unsigned long|unsigned long]
// [158] = ["arch_prctl", 2, int|unsigned long]
// [159] = ["adjtimex", 1, struct timex*]
// [160] = ["setrlimit", 2, unsigned int|struct rlimit*]
// [161] = ["chroot", 1, const char*]
// [162] = ["sync", 0]
// [163] = ["acct", 1, const char*]
// [164] = ["settimeofday", 2, struct timeval*|struct timezone*]
// [165] = ["mount", 5, char*|char*|char*|unsigned long|void*]
// [166] = ["umount2", 2, const char*|int]
// [167] = ["swapon", 2, const char*|int]
// [168] = ["swapoff", 1, const char*]
// [169] = ["reboot", 4, int|int|int|void*]
// [170] = ["sethostname", 2, char*|int]
// [171] = ["setdomainname", 2, char*|int]
// [172] = ["iopl", 1, unsigned int]
// [173] = ["ioperm", 3, unsigned long|unsigned long|int]
// [174] = ["create_module", 2, const char*|size_t]
// [175] = ["init_module", 3, void*|unsigned long|const char*]
// [176] = ["delete_module", 2, const char*|unsigned int]
// [177] = ["get_kernel_syms", 1, struct kernel_sym*]
// [178] = ["query_module", 5, const char*|int|void*|size_t|size_t]
// [179] = ["quotactl", 4, unsigned int|const char*|qid_t|void*]
// [180] = ["nfsservctl", 3, unsigned int|struct nfsctl_arg*|union nfsctl_res*]
// [181] = ["getpmsg", 5, int|int|struct old_sockaddr*|struct old_timeval*|void*]
// [182] = ["putpmsg", 5, int|int|const struct sockaddr*|int|const struct timeval*]
// [183] = ["afs_syscall", 0]
// [184] = ["tuxcall", 0]
// [185] = ["security", 0]
// [186] = ["gettid", 0]
// [187] = ["readahead", 3, int|loff_t|size_t]
// [188] = ["setxattr", 5, const char*|const char*|const void*|size_t|int]
// [189] = ["lsetxattr", 5, const char*|const char*|const void*|size_t|int]
// [190] = ["fsetxattr", 5, int|const char*|const void*|size_t|int]
// [191] = ["getxattr", 4, const char*|const char*|void*|size_t]
// [192] = ["lgetxattr", 4, const char*|const char*|void*|size_t]
// [193] = ["fgetxattr", 4, int|const char*|void*|size_t]
// [194] = ["listxattr", 3, const char*|char*|size_t]
// [195] = ["llistxattr", 3, const char*|char*|size_t]
// [196] = ["flistxattr", 3, int|char*|size_t]
// [197] = ["removexattr", 2, const char*|const char*]
// [198] = ["lremovexattr", 2, const char*|const char*]
// [199] = ["fremovexattr", 2, int|const char*]
// [200] = ["tkill", 2, pid_t|int]
// [201] = ["time", 1, time_t*]
// [202] = ["futex", 6, int|int|int|struct timespec*|int*|int]
// [203] = ["sched_setaffinity", 3, pid_t|unsigned int|unsigned long*]
// [204] = ["sched_getaffinity", 3, pid_t|unsigned int|unsigned long*]
// [205] = ["set_thread_area", 1, struct user_desc*]
// [206] = ["io_setup", 2, unsigned|int*]
// [207] = ["io_destroy", 1, unsigned]
// [208] = ["io_getevents", 5, aio_context_t|long|long|struct io_event*|struct timespec*]
// [209] = ["io_submit", 3, aio_context_t|long|struct iocb* const*]
// [210] = ["io_cancel", 3, aio_context_t|struct iocb*|struct io_event*]
// [211] = ["get_thread_area", 1, struct user_desc*]
// [212] = ["lookup_dcookie", 3, u64|char*|size_t]
// [213] = ["epoll_create", 1, int]
// [214] = ["epoll_ctl_old", 4, int|struct epoll_event*|struct epoll_event*|void*]
// [215] = ["epoll_wait_old", 4, int|struct epoll_event*|struct epoll_event*|void*]
// [216] = ["remap_file_pages", 5, unsigned long|unsigned long|unsigned long|unsigned long|unsigned long]
// [217] = ["getdents64", 3, unsigned int|struct linux_dirent64*|unsigned int]
// [218] = ["set_tid_address", 1, int*]
// [219] = ["restart_syscall", 0]
// [220] = ["semtimedop", 4, int|struct sembuf*|unsigned|int]
// [221] = ["fadvise64", 4, int|loff_t|size_t|int]
// [222] = ["timer_create", 3, clockid_t|struct sigevent*|timer_t*]
// [223] = ["timer_settime", 4, timer_t|int|const struct itimerspec*|struct itimerspec*]
// [224] = ["timer_gettime", 2, timer_t|struct itimerspec*]
// [225] = ["timer_getoverrun", 1, timer_t]
// [226] = ["timer_delete", 1, timer_t]
// [227] = ["clock_settime", 2, clockid_t|const struct timespec*]
// [228] = ["clock_gettime", 2, clockid_t|struct timespec*]
// [229] = ["clock_getres", 2, clockid_t|struct timespec*]
// [230] = ["clock_nanosleep", 4, clockid_t|int|const struct timespec*|struct timespec*]
// [231] = ["exit_group", 1, int]
// [232] = ["epoll_wait", 4, int|struct epoll_event*|int|int]
// [233] = ["epoll_ctl", 4, int|int|int|struct epoll_event*]
// [234] = ["tgkill", 3, pid_t|pid_t|int]
// [235] = ["utimes", 2, char*|struct timeval*]
// [236] = ["vserver", 6, int|int|u64*|u64*|u64*|u64*]
// [237] = ["mbind", 6, unsigned long|int|unsigned long*|unsigned long|unsigned long|unsigned int]
// [238] = ["set_mempolicy", 3, int|unsigned long*|unsigned long]
// [239] = ["get_mempolicy", 5, int|unsigned long*|unsigned long|unsigned long|unsigned long|unsigned long*]
// [240] = ["mq_open", 4, const char*|int|int|struct mq_attr*]
// [241] = ["mq_unlink", 1, const char*]
// [242] = ["mq_timedsend", 5, mqd_t|const char*|size_t|unsigned|int|const struct timespec*]
// [243] = ["mq_timedreceive", 5, mqd_t|char*|size_t|unsigned|int|const struct timespec*]
// [244] = ["mq_notify", 2, mqd_t|const struct sigevent*]
// [245] = ["mq_getsetattr", 3, mqd_t|const struct mq_attr*|struct mq_attr*]
// [246] = ["kexec_load", 4, unsigned long|unsigned long|struct kexec_segment*|unsigned long]
// [247] = ["waitid", 4, int|pid_t|struct siginfo*|int]
// [248] = ["add_key", 5, const char*|const char*|const void*|size_t|key_serial_t]
// [249] = ["request_key", 4, const char*|const char*|const char*|key_serial_t]
// [250] = ["keyctl", 5, int|unsigned long|unsigned long|unsigned long|unsigned long]
// [251] = ["ioprio_set", 3, int|int|int]
// [252] = ["ioprio_get", 2, int|int]
// [253] = ["inotify_init", 0]
// [254] = ["inotify_add_watch", 3, int|const char*|u32]
// [255] = ["inotify_rm_watch", 2, int|__s32]
// [256] = ["migrate_pages", 4, pid_t|unsigned long|const unsigned long*|const unsigned long*]
// [257] = ["openat", 4, int|const char*|int|mode_t]
// [258] = ["mkdirat", 3, int|const char*|mode_t]
// [259] = ["mknodat", 4, int|const char*|mode_t|dev_t]
// [260] = ["fchownat", 5, int|const char*|uid_t|gid_t|int]
// [261] = ["futimesat", 3, int|const char*|struct timeval*]
// [262] = ["newfstatat", 4, int|const char*|struct stat*|int]
// [263] = ["unlinkat", 3, int|const char*|int]
// [264] = ["renameat", 4, int|const char*|int|const char*]
// [265] = ["linkat", 5, int|const char*|int|const char*|int]
// [266] = ["symlinkat", 3, const char*|int|const char*]
// [267] = ["readlinkat", 4, int|const char*|char*|int]
// [268] = ["fchmodat", 4, int|const char*|mode_t|int]
// [269] = ["faccessat", 4, int|const char*|int|int]
// [270] = ["pselect6", 6, int|fd_set*|fd_set*|fd_set*|struct timespec*|void*]
// [271] = ["ppoll", 5, struct pollfd*|nfds_t|struct timespec*|const sigset_t*|size_t]
// [272] = ["unshare", 1, unsigned long]
// [273] = ["set_robust_list", 2, struct robust_list_head*|size_t]
// [274] = ["get_robust_list", 3, int|struct robust_list_head**|size_t*]
// [275] = ["splice", 6, int|loff_t*|int|loff_t*|size_t|unsigned int]
// [276] = ["tee", 4, int|int|size_t|unsigned int]
// [277] = ["sync_file_range", 4, int|off64_t|off64_t|size_t]
// [278] = ["vmsplice", 4, int|struct iovec*|unsigned long|int]
// [279] = ["move_pages", 6, pid_t|int|void*|const int*|int*|int]
// [280] = ["utimensat", 4, int|const char*|struct timespec*|int]
// [281] = ["epoll_pwait", 5, int|struct epoll_event*|int|int|const sigset_t*]
// [282] = ["signalfd", 3, int|sigset_t*|int]
// [283] = ["timerfd_create", 2, int|int]
// [284] = ["eventfd", 1, unsigned int]
// [285] = ["fallocate", 4, int|int|off_t|off_t]
// [286] = ["timerfd_settime", 4, int|int|const struct itimerspec*|struct itimerspec*]
// [287] = ["timerfd_gettime", 2, int|struct itimerspec*]
// [288] = ["accept4", 4, int|struct sockaddr*|socklen_t*|int]
// [289] = ["signalfd4", 4, int|sigset_t*|int|int]
// [290] = ["eventfd2", 2, unsigned int|int]
// [291] = ["epoll_create1", 1, int]
// [292] = ["dup3", 3, unsigned int|unsigned int|int]
// [293] = ["pipe2", 2, int*|int]
// [294] = ["inotify_init1", 1, int]
// [295] = ["preadv", 4, unsigned long|const struct iovec*|unsigned long|unsigned long]
// [296] = ["pwritev", 4, unsigned long|const struct iovec*|unsigned long|unsigned long]
// [297] = ["rt_tgsigqueueinfo", 4, pid_t|pid_t|int|siginfo_t*]
// [298] = ["perf_event_open", 5, struct perf_event_attr*|pid_t|int|int|int]
// [299] = ["recvmmsg", 5, int|struct mmsghdr*|unsigned int|unsigned int|struct timespec*]

// 300	fanotify_init
// 301	fanotify_mark
// 302	prlimit64
// 303	name_to_handle_at
// 304	open_by_handle_at
// 305	clock_adjtime
// 306	syncfs
// 307	sendmmsg
// 308	setns
// 309	getcpu
// 310	process_vm_readv
// 311	process_vm_writev
// 312	kcmp
// 313	finit_module
// 314	sched_setattr
// 315	sched_getattr
// 316	renameat2
// 317	seccomp
// 318	getrandom
// 319	memfd_create
// 320	kexec_file_load
// 321	bpf
// 322	execveat
// 323	userfaultfd
// 324	membarrier
// 325	mlock2
// 326	copy_file_range
// 327	preadv2
// 328	pwritev2
// 329	pkey_mprotect
// 330	pkey_alloc
// 331	pkey_free
// 332	statx
// 333	io_pgetevents
// 334	rseq

// [300] = ["fanotify_init", 2, unsigned int|unsigned int]
// [301] = ["fanotify_mark", 5, int|int|u64|u64|int]
// [302] = ["prlimit64", 4, pid_t|unsigned int|const struct rlimit*|struct rlimit*]
// [303] = ["name_to_handle_at", 5, int|const char*|struct file_handle*|int|int]
// [304] = ["open_by_handle_at", 5, int|const struct file_handle*|int|int|int]
// [305] = ["clock_adjtime", 2, clockid_t|struct timex*]
// [306] = ["syncfs", 1, int]
// [307] = ["sendmmsg", 4, int|struct mmsghdr*|unsigned int|unsigned int]
// [308] = ["setns", 2, int|int]
// [309] = ["getcpu", 3, unsigned*|unsigned*|struct getcpu_cache*]
// [310] = ["process_vm_readv", 6, pid_t|const struct iovec*|unsigned long|const struct iovec*|unsigned long|unsigned long]
// [311] = ["process_vm_writev", 6, pid_t|const struct iovec*|unsigned long|const struct iovec*|unsigned long|unsigned long]
// [312] = ["kcmp", 5, pid_t|pid_t|int|unsigned long|unsigned long]
// [313] = ["finit_module", 3, int|const char*|int]
// [314] = ["sched_setattr", 3, pid_t|struct sched_attr*|unsigned int]
// [315] = ["sched_getattr", 4, pid_t|struct sched_attr*|unsigned int|unsigned int]
// [316] = ["renameat2", 5, int|const char*|int|const char*|unsigned|int]
// [317] = ["seccomp", 3, unsigned|int|void*]
// [318] = ["getrandom", 3, char*|size_t|unsigned int]
// [319] = ["memfd_create", 2, const char*|unsigned int]
// [320] = ["kexec_file_load", 5, int|int|int|const char*|const char*]
// [321] = ["bpf", 3, int|union bpf_attr*|unsigned int]
// [322] = ["execveat", 5, int|const char*|char* const*|char* const*|int]
// [323] = ["userfaultfd", 1, int]
// [324] = ["membarrier", 2, int|int]
// [325] = ["mlock2", 3, unsigned long|size_t|int]
// [326] = ["copy_file_range", 6, int|loff_t*|int|loff_t*|size_t|unsigned int]
// [327] = ["preadv2", 5, unsigned long|const struct iovec*|unsigned long|unsigned long|loff_t]
// [328] = ["pwritev2", 5, unsigned long|const struct iovec*|unsigned long|unsigned long|loff_t]
// [329] = ["pkey_mprotect", 4, unsigned long|size_t|int|unsigned long]
// [330] = ["pkey_alloc", 2, unsigned long|unsigned long]
// [331] = ["pkey_free", 1, unsigned long]
// [332] = ["statx", 5, int|const char*|unsigned|int|struct statx*]
// [333] = ["io_pgetevents", 6, aio_context_t|long|long|struct io_event*|struct timespec*|const struct __sysctl_args*]
// [334] = ["rseq", 1, void*]

#endif